language: ruby
bundler_args: "--without development --deployment --jobs=3 --retry=3"
cache:
  directories:
  - vendor/bundle

rvm:
- 2.1.1

branches:
  only:
  - master
  - production

gemfile:
- Gemfile

env:
- DB=mysql

before_script:
- cp config/database.travis.yml config/database.yml

script:
- RAILS_ENV=test bundle exec rake db:create
- RAILS_ENV=test bundle exec rake db:migrate
- RAILS_ENV=test bundle exec rake db:test:prepare
- RAILS_ENV=test bundle exec rake spec

after_success:
- echo "$TRAVIS_BRANCH"
- if [[ "$TRAVIS_BRANCH" == "master" ]] ; then script/deploy.sh; fi

notifications:
  slack:
    rooms:
      secure: pUU8Uhbni2AFAlEYYP1OQmvp
