language: ruby
cache:
  bundler: true

rvm:
- 2.1.1

branches:
  only:
  - master
  - production

gemfile:
- Gemfile

env:
- DB=mysql

before_script:
- cp config/database.travis.yml config/database.yml
- mysql -e 'create database fc2play_test;'

script:
- bundle exec rake db:migrate RAILS_ENV=test
- bundle exec rake db:test:prepare RAILS_ENV=test
- bundle exec rake spec RAILS_ENV=test

after_success:
- echo "$TRAVIS_BRANCH"
- if [[ "$TRAVIS_BRANCH" == "master" ]] ; then script/deploy.sh; fi

notifications:
  slack:
    secure: R/BrmCA+DyMmwI87lrN0tByRn2SsyPEIMis+wud9K8XjxBXTp60MYPluAyPs+3+CwgMQ3/34ZdlBIW9790B1k3MLs0QTeUoAf0819Y4Tin4UjGw+iJAGgog09EDRiGdNesJnNSBemiKQNJjAc3GbcHprwUaen/E/HDBckol9wIo=
